### ISSUE TITLE
Possible typo in a spec

### ISSUE THREAD

**Issue by Chlorophytus** [GPrimola/yamel#3]
I noticed VSCode warn me about this, but this could probably be an `encode!`. At line 15 of `lib/yamel.ex`. I have corrected this in the PR I am about to create in a few days for the issue 1 (not tagging because these two are unrelated).
```elixir
# ...
  @spec encode(Yamel.t()) :: yaml()
  def encode!(map_or_list)
# ...
```

If this isn't a typo then feel free to tell me, I am still learning.

**Comment by GPrimola** [comment]
Hey @Chlorophytus

Yes, this is definitely a typo, thank you for noticing that and the interest on the project!

Unfortunately I won't account this as a Hacktoberfest thing. But I'll open another issue so who wants to improve the documentation for this function to fix this typo.
