### ISSUE TITLE
[Documentation] Document Yamel.decode!/1 and Yamel.decode/1

### ISSUE THREAD

**Issue by GPrimola** [GPrimola/yamel#4]
Write a documentation following [this guidelines](https://hexdocs.pm/elixir/1.10.0/writing-documentation.html) for [`Yamel.decode!/1`](https://github.com/GPrimola/yamel/blob/master/lib/yamel.ex#L10) and for [`Yamel.decode/1`](https://github.com/GPrimola/yamel/blob/master/lib/yamel.ex#L13).

PS: an important highlight is the [Doctests](https://hexdocs.pm/elixir/1.10.0/writing-documentation.html#doctests) session, as it's part of the documentation!

**Comment by francolucas** [comment]
Hey man! I'd like to take this one. :)

**Comment by GPrimola** [comment]
Fixed by #9 and #14
